project:
  type: book

book:
  title: "Some Notes in Linear Algebra"
  author: "Scissor"
  date: today
  repo-url: "https://github.com/c3b2aNaN/linalg"
  repo-actions: [issue]
  chapters:
    - index.qmd
    # - notations.qmd
    - part: "Part 1: Linear Equations in Linear Algebra"
      chapters:
      - part1/chap1.7.qmd
      - part1/chap1.8.qmd
      - part1/chap1.9.qmd
      - part1/sum.qmd
      - part1/qa.qmd
    - references.qmd

bibliography: references.bib

execute:
  echo: false

format:
  html:
    number-depth: 1
    theme:
      light: flatly
      dark: darkly
  # pdf:
  #   header-includes:
  #     - \usepackage{amsmath}
  #   number-depth: 0
  #   pdf-engine: pdflatex
  #   documentclass: scrreprt

filters:
  - callouty-theorem

callouty-theorem:
  thm:
    override-title: false # do not override the title of the callout (title won't show when `appearance` set to `simple` or `minimal`)
    callout: # parameters of the wrapping callout. see Quarto documentation of callouts for more details
      type: note
      appearance: minimal
  prp:
    override-title: false
    callout:
      type: note
      appearance: minimal
  exr:
    override-title: false
    callout:
      type: tip
      appearance: minimal
  proof: # also support wrapping proof-like environments
    override-title: true # override the title of the callout by the name of the theorem
    callout:
      type: note
      appearance: default
      collapse: false
      icon: true
  solution:
    override-title: true
    callout:
      type: note
      appearance: default
      collapse: false
      icon: true
  remark:
    override-title: true
    callout:
      type: tip
      appearance: default
      collapse: false
      icon: true

  # theorems types not specified in the metadata will be rendered as is
  cor: default # calloutify corollaries with default style
  def:
    override-title: true
    callout: default # also support default style here
