# Preface {.unnumbered}

::: {.callout-tip}

Recommended Reading:

- [Part 4](part4/chap4.6.qmd#prp-4-6-2)
- [Part 1](part1/chap1.7.qmd)
- [3.1 Introduction to Determinants](part3/chap3.1.qmd)

Not Recommended Reading:

- [2.5 Matrix Factorizations](part2/chap2.5.qmd) (Reason: flawed proofs)

Pending:

- [3.2 \[R\] Number Theory? - Quotient Spaces](part3/chap3.2x.qmd#quotient-spaces)
:::

This is a book about some notes when the author (currently a 12th grader) is taking an honor course on college linear algebra in high school. Subjected to the author's knowledge level and the fact that the course targets high school students, this book may include some inaccurate parts. The author will try to avoid making mistakes, but in case you find a potential error while reading, please consult your instructor (or ChatGPT, Grok, DeepSeek, etc.).

The textbook used in the course, *Linear Algebra and Its Applications 5th Edition*  [@linalgapp], serves as the basis of this book.

The indices of theorems, exercises, etc. may not be the same in the textbook. For example, "Theorem 1.1 (Theorem 7)" under Section 1.7 refers to Theorem 7 in Section 1.7 in the textbook, but it will sometimes be referred to as Theorem 1.1 in this book. Be cautious of the actual index.

"[R]" in the title of some chapters means **r**andom thoughts and further explorations.

A reminder before all: **do not try to prove definitions.** They are called **definitions** because they are **defined**. What we prove are theorems. \begin{align}\end{align}