## 1.9 The Matrix of a Linear Transformation {.unnumbered}

::: {#thm-1-9-10}

## Theorem 10

Let $T: \mathbb{R}^n \to \mathbb{R}^m$ be a linear transformation. Then there exists a unique matrix $A$ such that
$$T(\mathbf{x})=A\mathbf{x}\quad\text{for all }\mathbf{x}\text{ in }\mathbb{R}^n$$
In fact, $A$ is the $m\times n$ matrix whose $j$ th column is the vector $T(\mathbf{e}_j)$, where $\mathbf{e}_j$ is the $j$ th column of the identity matrix in $\mathbb{R}^n$:
$$A=\begin{bmatrix}T(\mathbf{e}_1) & \cdots & T(\mathbf{e}_n)\end{bmatrix}$$
:::

::: {.proof}

## Proof of [@thm-1-9-10]

The theorem says that every $T: \mathbb{R}^n \to \mathbb{R}^m$ can be represented as a matrix transformation, but we just said not all linear transformations can be represented by a matrix. However, there's a condition in this theorem. That is, $T$ maps a vector in $\mathbb{R}^n$, a finite vector space, to a vector in $\mathbb{R}^m$, also a finite vector space.

The proof of the existence is on both the textbook and the previous chapter in this book (a partial proof), so we prove only the uniqueness here.

If the matrix $A$ isn't unique, let $B=\begin{bmatrix}\mathbf{b}_1 & \cdots & \mathbf{b}_n\end{bmatrix}\neq A$ be another matrix.

$$T(\mathbf{e}_j)=B\mathbf{e}_j=0\mathbf{b}_1+\dots+0\mathbf{b}_{j-1}+\mathbf{b}_j+0\mathbf{b}_{j+1}+\dots+0\mathbf{b}_n=\mathbf{b}_j$$

However, we know that the $j$ th column of $A$ is also $T(\mathbf{e}_j)$. Thus, for every $1\leq j\leq n$, the $j$ th columns of $A$ and $B$ are equal, so $A=B$.
:::

::: {.callout-tip}

## If $\mathbf{e}_1,\dots,\mathbf{e}_n$ are any linear independent set of vectors

Suppose we need to find $T(\mathbf{x})$. Since $\mathbf{e}_1,\dots,\mathbf{e}_n$ are linear independent, $\begin{bmatrix}\mathbf{e}_1 & \cdots & \mathbf{e}_n\end{bmatrix}$ has a pivot position at each row. The equation $\begin{bmatrix}\mathbf{e}_1 & \cdots & \mathbf{e}_n\end{bmatrix}\mathbf{t}=\mathbf{x}$ has a unique solution.
$$\mathbf{t}=\begin{bmatrix}\mathbf{e}_1 & \cdots & \mathbf{e}_n\end{bmatrix}^{-1} \mathbf{x}$$
\begin{align*}
T(\mathbf{x})&=T(t_1\mathbf{e}_1+\dots+t_n\mathbf{e}_n) \\
&=t_1 T(\mathbf{e}_1)+\dots+t_n T(\mathbf{e}_n) \\
&=\begin{bmatrix}T(\mathbf{e}_1) & \cdots & T(\mathbf{e}_n)\end{bmatrix}\mathbf{t} \\
&=\left(\begin{bmatrix}T(\mathbf{e}_1) & \cdots & T(\mathbf{e}_n)\end{bmatrix}\begin{bmatrix}\mathbf{e}_1 & \cdots & \mathbf{e}_n\end{bmatrix}^{-1}\right)\mathbf{x}
\end{align*}
:::